name: Code quality tests

# Trigger the workflow on push or pull request
# events but only for the master branch:
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  isort:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install isort
        run: |
          python -m pip install --upgrade pip
          pip install isort==5.4.2
      - name: Run isort
        run: |
          isort --version
          isort -c .

  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8==3.8.3
      - name: Run flake8
        run: |
          flake8 --version
          flake8
